//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFJ.Repository.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public Nullable<int> ClientID { get; set; }
        public string ClientName { get; set; }
        public int FormID { get; set; }
        public string FormName { get; set; }
        public Nullable<int> RequestID { get; set; }
        public int FieldID { get; set; }
        public string FieldName { get; set; }
        public string FieldValue { get; set; }
    }
}
