//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFJ.Repository.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class author
    {
        public int authorID { get; set; }
        public string loginName { get; set; }
        public string loginPassword { get; set; }
        public string authorFName { get; set; }
        public string authorLName { get; set; }
        public string authorEmail { get; set; }
        public string authorPhone { get; set; }
        public Nullable<int> authorLevel { get; set; }
        public Nullable<byte> authorEmailNotification { get; set; }
        public string toolsControl { get; set; }
        public string tableControl { get; set; }
        public string sectionAccess { get; set; }
        public string pageAccess { get; set; }
        public string EWImageDir { get; set; }
        public Nullable<byte> EWShowFullScreenButton { get; set; }
        public Nullable<byte> EWShowBoldButton { get; set; }
        public Nullable<byte> EWShowUnderlineButton { get; set; }
        public Nullable<byte> EWShowItalicButton { get; set; }
        public Nullable<byte> EWShowStrikethroughButton { get; set; }
        public Nullable<byte> EWShowNumberListButton { get; set; }
        public Nullable<byte> EWShowBulletListButton { get; set; }
        public Nullable<byte> EWShowDecreaseIndentButton { get; set; }
        public Nullable<byte> EWShowIncreaseIndentButton { get; set; }
        public Nullable<byte> EWShowLeftAlignButton { get; set; }
        public Nullable<byte> EWShowCenterAlignButton { get; set; }
        public Nullable<byte> EWShowRightAlignButton { get; set; }
        public Nullable<byte> EWShowJustifyButton { get; set; }
        public Nullable<byte> EWShowHorizontalRuleButton { get; set; }
        public Nullable<byte> EWShowLinkButton { get; set; }
        public Nullable<byte> EWShowAnchorButton { get; set; }
        public Nullable<byte> EWShowMailLinkButton { get; set; }
        public Nullable<byte> EWShowHelpButton { get; set; }
        public Nullable<byte> EWShowFontList { get; set; }
        public Nullable<byte> EWShowSizeList { get; set; }
        public Nullable<byte> EWShowFormatList { get; set; }
        public Nullable<byte> EWShowStyleList { get; set; }
        public Nullable<byte> EWShowForeColorButton { get; set; }
        public Nullable<byte> EWShowBackColorButton { get; set; }
        public Nullable<byte> EWShowTableButton { get; set; }
        public Nullable<byte> EWShowFormButton { get; set; }
        public Nullable<byte> EWShowImageButton { get; set; }
        public Nullable<byte> EWShowTextBoxButton { get; set; }
        public Nullable<byte> EWShowSymbolButton { get; set; }
        public Nullable<byte> EWShowPropertiesButton { get; set; }
        public Nullable<byte> EWShowCleanHTMLButton { get; set; }
        public Nullable<byte> EWShowAbsolutePositionButton { get; set; }
        public Nullable<byte> EWShowGuidelinesButton { get; set; }
        public Nullable<byte> EWShowSpellingButton { get; set; }
        public Nullable<byte> EWShowRemoveTextFormattingButton { get; set; }
        public Nullable<byte> EWShowSuperScriptButton { get; set; }
        public Nullable<byte> EWShowSubScriptButton { get; set; }
        public Nullable<byte> EWDisableSourceMode { get; set; }
        public Nullable<byte> EWDisablePreviewMode { get; set; }
        public Nullable<byte> EWDisableImageUploading { get; set; }
        public Nullable<byte> EWDisableImageDeleting { get; set; }
        public Nullable<byte> EWDisableXHTMLFormatting { get; set; }
        public Nullable<byte> EWDisableSingleLineReturn { get; set; }
        public Nullable<byte> EWDisableInsertImageFromWeb { get; set; }
        public Nullable<byte> EWShowFlashButton { get; set; }
        public Nullable<byte> EWDisableFlashUploading { get; set; }
        public Nullable<byte> EWDisableFlashDeleting { get; set; }
        public Nullable<byte> EWDisableInsertFlashFromWeb { get; set; }
        public Nullable<int> SessionTimeout { get; set; }
        public Nullable<byte> active { get; set; }
    }
}
