//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFJ.Repository.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class clickCount
    {
        public int clickCountID { get; set; }
        public Nullable<int> mailingID { get; set; }
        public string redirURL { get; set; }
        public Nullable<int> clickCount1 { get; set; }
    }
}
