//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFJ.Repository.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class columnInfo
    {
        public int columnInfoID { get; set; }
        public string tableName { get; set; }
        public string columnName { get; set; }
        public string promptName { get; set; }
        public Nullable<int> sequenceID { get; set; }
        public string helpText { get; set; }
        public string imageSelectDir { get; set; }
        public Nullable<int> textareaRows { get; set; }
        public Nullable<int> textareaCols { get; set; }
        public string lookupTable { get; set; }
        public string lookupIDColumn { get; set; }
        public string lookupFieldName { get; set; }
        public string lookupFieldName2 { get; set; }
        public string dropdownListQuery { get; set; }
        public Nullable<int> hiddenField { get; set; }
        public string hiddenValue { get; set; }
        public Nullable<byte> coolEditor { get; set; }
        public string dateFmt { get; set; }
        public string tinyintText { get; set; }
    }
}
