//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFJ.Repository.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class currency
    {
        public int currencyID { get; set; }
        public string currencyCode { get; set; }
        public string currencyName { get; set; }
        public Nullable<int> sequenceID { get; set; }
    }
}
