//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFJ.Repository.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class distributionList
    {
        public int distributionListID { get; set; }
        public string distributionListName { get; set; }
        public Nullable<byte> useWinHttp { get; set; }
        public string httpURL { get; set; }
        public string dsConnStr { get; set; }
        public string dsLoginName { get; set; }
        public string dsPassword { get; set; }
        public string dsQuery { get; set; }
    }
}
