//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFJ.Repository.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Document()
        {
            this.documentClients = new HashSet<documentClient>();
        }
    
        public int ID { get; set; }
        public string DocumentName { get; set; }
        public string FileName { get; set; }
        public string DocumentType { get; set; }
        public string ProjectType { get; set; }
        public string FormType { get; set; }
        public Nullable<int> ClientID { get; set; }
        public Nullable<int> PracticeAreaID { get; set; }
        public string WFJFileNbr { get; set; }
        public Nullable<int> Days { get; set; }
        public string Description { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<int> EmployeeCategoryID { get; set; }
        public Nullable<int> StateCodeID { get; set; }
        public Nullable<int> DocumentTypeID { get; set; }
        public string ProjectTypeID { get; set; }
        public string FormTypeID { get; set; }
        public Nullable<int> SeqNo { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Code Code { get; set; }
        public virtual Code Code1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<documentClient> documentClients { get; set; }
        public virtual PracticeArea PracticeArea { get; set; }
    }
}
