//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFJ.Repository.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentUsage
    {
        public int ID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> DocumentID { get; set; }
        public string DocumentName { get; set; }
        public Nullable<System.DateTime> UsageDate { get; set; }
        public string IPAddress { get; set; }
    }
}
