//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFJ.Repository.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class element
    {
        public int elementID { get; set; }
        public string elementName { get; set; }
        public Nullable<int> typeID { get; set; }
        public Nullable<int> elementCategoryID { get; set; }
        public Nullable<System.DateTime> starttime { get; set; }
        public Nullable<System.DateTime> endtime { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public Nullable<System.DateTime> updateDate { get; set; }
        public string SQLQuery { get; set; }
        public Nullable<int> authorID { get; set; }
        public Nullable<int> draftExists { get; set; }
        public Nullable<int> draftLocked { get; set; }
        public Nullable<byte> lockedElement { get; set; }
        public Nullable<byte> coreElement { get; set; }
        public string elementValue { get; set; }
        public string elementDraftValue { get; set; }
    }
}
