//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFJ.Repository.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventDate
    {
        public int EventDateID { get; set; }
        public Nullable<int> EventID { get; set; }
        public string EventDateName { get; set; }
        public string EventDate1 { get; set; }
        public string EventTime { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Location { get; set; }
        public Nullable<int> Status { get; set; }
        public string EventDateSummary { get; set; }
    }
}
