//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFJ.Repository.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public int EventID { get; set; }
        public string EventName { get; set; }
        public string Summary { get; set; }
        public string HowtoRegister { get; set; }
        public Nullable<int> EventLimit { get; set; }
        public string Document { get; set; }
        public string URL { get; set; }
        public string Sponsors { get; set; }
        public Nullable<int> Category { get; set; }
        public Nullable<int> Status { get; set; }
        public string ContactName { get; set; }
        public string ContactAddress { get; set; }
        public string ContactCity { get; set; }
        public string ContactState { get; set; }
        public string ContactPostalCode { get; set; }
        public string ContactTelephone { get; set; }
        public string ContactEMail { get; set; }
    }
}
