//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFJ.Repository.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class formDataSheet
    {
        public int formDataSheetID { get; set; }
        public int formID { get; set; }
        public Nullable<int> caseFieldID { get; set; }
        public Nullable<int> CustomerAccountFieldID { get; set; }
        public Nullable<int> balanceDueFieldID { get; set; }
        public Nullable<int> addressFieldID { get; set; }
        public Nullable<int> contactFieldID { get; set; }
        public Nullable<int> projectFieldID { get; set; }
        public Nullable<int> customerPhonefieldID { get; set; }
        public Nullable<int> customerFaxFieldID { get; set; }
        public Nullable<int> CustomerCellFieldID { get; set; }
        public Nullable<int> CustomerEmailFieldID { get; set; }
        public Nullable<int> billTypeFieldID { get; set; }
        public Nullable<int> practiceGroupFieldID { get; set; }
        public Nullable<int> billingRateFieldID { get; set; }
    }
}
