//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFJ.Repository.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class hiddenRequestNote
    {
        public int hiddenRequestNoteID { get; set; }
        public Nullable<int> userID { get; set; }
        public Nullable<int> requestID { get; set; }
        public Nullable<int> noteID { get; set; }
    }
}
