//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFJ.Repository.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class hrDocument
    {
        public int hrDocumentID { get; set; }
        public string documentName { get; set; }
        public string filename { get; set; }
        public string linkURL { get; set; }
        public Nullable<int> sequenceID { get; set; }
    }
}
