//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFJ.Repository.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LetterSchedule
    {
        public int LetterScheduleID { get; set; }
        public Nullable<int> LetterID { get; set; }
        public Nullable<int> StatusCode { get; set; }
        public Nullable<int> RequestDays { get; set; }
        public Nullable<int> CompletionDays { get; set; }
    }
}
