//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFJ.Repository.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class mailingList
    {
        public int mailingListID { get; set; }
        public Nullable<int> clientID { get; set; }
        public string mailingListName { get; set; }
        public string mailingListFilename { get; set; }
        public Nullable<System.DateTime> uploadDate { get; set; }
        public Nullable<int> emailColumn { get; set; }
        public Nullable<byte> skipFirstColumn { get; set; }
    }
}
