//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFJ.Repository.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class mailformResult
    {
        public int mailformResultID { get; set; }
        public Nullable<int> mailformID { get; set; }
        public Nullable<System.DateTime> submitDate { get; set; }
        public string field01result { get; set; }
        public string field02result { get; set; }
        public string field03result { get; set; }
        public string field04result { get; set; }
        public string field05result { get; set; }
        public string field06result { get; set; }
        public string field07result { get; set; }
        public string field08result { get; set; }
        public string field09result { get; set; }
        public string field10result { get; set; }
        public string field11result { get; set; }
        public string field12result { get; set; }
        public string field13result { get; set; }
        public string field14result { get; set; }
        public string field15result { get; set; }
        public string field16result { get; set; }
        public string field17result { get; set; }
        public string field18result { get; set; }
        public string field19result { get; set; }
        public string field20result { get; set; }
        public string field21result { get; set; }
        public string field22result { get; set; }
        public string field23result { get; set; }
        public string field24result { get; set; }
        public string field25result { get; set; }
        public string field26result { get; set; }
        public string field27result { get; set; }
        public string field28result { get; set; }
        public string field29result { get; set; }
        public string field30result { get; set; }
    }
}
