//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFJ.Repository.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class message
    {
        public int messageID { get; set; }
        public string messageName { get; set; }
        public Nullable<byte> messageFlag { get; set; }
        public string messageDesc { get; set; }
        public string messageText { get; set; }
    }
}
