//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFJ.Repository.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public int NewsID { get; set; }
        public string Headline { get; set; }
        public string ShortText { get; set; }
        public string StoryText { get; set; }
        public string LinkURL { get; set; }
        public Nullable<byte> NewWindow { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> Category { get; set; }
        public Nullable<int> ShowWholeStory { get; set; }
        public Nullable<int> SeqNo { get; set; }
    }
}
