//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFJ.Repository.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Newsletter
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> NewsletterDate { get; set; }
        public string Title { get; set; }
        public string FileName { get; set; }
        public string Contents { get; set; }
        public Nullable<int> NewsletterType { get; set; }
    }
}
