//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFJ.Repository.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int ID { get; set; }
        public Nullable<int> FormID { get; set; }
        public Nullable<int> ServiceDeadlineFieldID { get; set; }
        public Nullable<int> FirstDateFieldID { get; set; }
        public Nullable<int> LastDateFieldID { get; set; }
        public Nullable<int> DateFiledFieldID { get; set; }
        public Nullable<int> DatePaidFieldID { get; set; }
        public Nullable<int> DateReleasedFieldID { get; set; }
    }
}
