//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFJ.Repository.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class page
    {
        public int pageID { get; set; }
        public int sectionID { get; set; }
        public string pageName { get; set; }
        public Nullable<int> childOfPageID { get; set; }
        public string navName { get; set; }
        public Nullable<int> sequenceID { get; set; }
        public string templateFile { get; set; }
        public Nullable<byte> includeOnMenu { get; set; }
        public Nullable<byte> status { get; set; }
        public Nullable<byte> underConstruction { get; set; }
        public Nullable<byte> approvedDraft { get; set; }
        public Nullable<byte> altHeader { get; set; }
        public Nullable<int> altPageID { get; set; }
        public string linkText { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public Nullable<System.DateTime> updateDate { get; set; }
        public string shortcutName { get; set; }
        public string altURL { get; set; }
        public Nullable<byte> includeOnSitemap { get; set; }
        public string metakeywords { get; set; }
        public string metadescription { get; set; }
    }
}
