//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFJ.Repository.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int ID { get; set; }
        public Nullable<int> RequestID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public Nullable<System.DateTime> remitDate { get; set; }
        public string CheckNumber { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<double> WFJFees { get; set; }
        public Nullable<int> PaymentTypeID { get; set; }
        public Nullable<int> currencyID { get; set; }
    }
}
