//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFJ.Repository.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionnaireRespons
    {
        public int ID { get; set; }
        public Nullable<int> RequestID { get; set; }
        public Nullable<int> Field1Nbr { get; set; }
        public Nullable<int> Field2Nbr { get; set; }
        public Nullable<int> Field3Nbr { get; set; }
        public Nullable<int> Field4Nbr { get; set; }
        public string FieldValue1 { get; set; }
        public string FieldValue2 { get; set; }
        public string FieldValue3 { get; set; }
        public string FieldValue4 { get; set; }
        public string FieldValue5 { get; set; }
        public string FieldValue6 { get; set; }
    }
}
