//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFJ.Repository.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestNotice
    {
        public int RequestNoticeID { get; set; }
        public Nullable<int> RequestID { get; set; }
        public Nullable<System.DateTime> NoticeDate { get; set; }
        public string RecipientList { get; set; }
        public string NoticeSubject { get; set; }
        public string NoticeText { get; set; }
    }
}
