//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFJ.Repository.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SearchResult
    {
        public int ID { get; set; }
        public Nullable<int> SessionID { get; set; }
        public string LinkURL { get; set; }
        public string LinkDescription { get; set; }
        public Nullable<System.DateTime> DateField { get; set; }
        public string GroupName { get; set; }
        public Nullable<int> GroupSeqNo { get; set; }
        public Nullable<System.DateTime> RecordDate { get; set; }
    }
}
