//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFJ.Repository.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class section
    {
        public int sectionID { get; set; }
        public string sectionName { get; set; }
        public Nullable<int> sequenceID { get; set; }
        public Nullable<byte> includeOnMenu { get; set; }
        public Nullable<byte> status { get; set; }
        public string pageHeaderImage { get; set; }
        public string pageHeaderImage2 { get; set; }
        public string navImage { get; set; }
        public string navRolloverImage { get; set; }
        public Nullable<int> sectionPageID { get; set; }
        public string dropdown1MenuSize { get; set; }
        public string dropdown2MenuSize { get; set; }
        public string dropdown3MenuSize { get; set; }
        public string dropdown4MenuSize { get; set; }
        public string dropdownMenuOffset { get; set; }
    }
}
