//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFJ.Repository.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatusCode
    {
        public int ID { get; set; }
        public Nullable<int> StatusCode1 { get; set; }
        public Nullable<int> ClientID { get; set; }
        public Nullable<int> FormID { get; set; }
        public Nullable<int> StatusLevel { get; set; }
        public Nullable<int> SeqNo { get; set; }
        public string Description { get; set; }
        public string DescriptionLong { get; set; }
        public Nullable<byte> deleteIt { get; set; }
        public Nullable<int> complianceDuration { get; set; }
        public Nullable<byte> OnCollectorComplianceReport { get; set; }
    }
}
