//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFJ.Repository.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tableInfo
    {
        public int tableInfoID { get; set; }
        public string tableName { get; set; }
        public string tableOrderBy { get; set; }
        public string tableFirstCol { get; set; }
        public string tableListCols { get; set; }
        public Nullable<int> sequenceID { get; set; }
        public Nullable<byte> showInAdmin { get; set; }
        public Nullable<int> pageSize { get; set; }
        public string joinTable1 { get; set; }
        public string joinCol1 { get; set; }
        public string joinTable2 { get; set; }
        public string joinCol2 { get; set; }
        public string joinTable3 { get; set; }
        public string joinCol3 { get; set; }
        public string adminName { get; set; }
        public Nullable<byte> authoredTable { get; set; }
    }
}
