//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFJ.Repository.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableRow
    {
        public int TableRowID { get; set; }
        public Nullable<int> QuestionID { get; set; }
        public string RowNbr { get; set; }
        public string RowTitle { get; set; }
        public Nullable<int> SeqNo { get; set; }
        public Nullable<int> NumberOfRows { get; set; }
    }
}
