CREATE TABLE [dbo].[mailforms] (
    [mailformID]         INT            IDENTITY (1, 1) NOT NULL,
    [formname]           VARCHAR (50)   NULL,
    [emailRecipients]    VARCHAR (100)  NULL,
    [emailRecipientsCC]  VARCHAR (100)  NULL,
    [emailRecipientsBCC] VARCHAR (100)  NULL,
    [emailSubject]       VARCHAR (100)  NULL,
    [emailReplyTo]       VARCHAR (50)   NULL,
    [emailFrom]          VARCHAR (50)   NULL,
    [nextpageID]         INT            NULL,
    [submitButtonImage]  VARCHAR (50)   NULL,
    [submitButtonText]   VARCHAR (30)   NULL,
    [listFieldNames]     TINYINT        NULL,
    [storeResults]       TINYINT        NULL,
    [preFormHTML]        VARCHAR (500)  NULL,
    [postFormHTML]       VARCHAR (500)  NULL,
    [requiredColor]      VARCHAR (10)   NULL,
    [field01name]        VARCHAR (50)   NULL,
    [field01title]       VARCHAR (100)  NULL,
    [field01typeID]      INT            NULL,
    [field01value]       VARCHAR (100)  NULL,
    [field01len]         INT            NULL,
    [field01lines]       INT            NULL,
    [field01required]    TINYINT        NULL,
    [field01validation]  VARCHAR (50)   NULL,
    [field01post]        VARCHAR (200)  NULL,
    [field02name]        VARCHAR (50)   NULL,
    [field02title]       VARCHAR (100)  NULL,
    [field02typeID]      INT            NULL,
    [field02value]       VARCHAR (100)  NULL,
    [field02len]         INT            NULL,
    [field02lines]       INT            NULL,
    [field02required]    TINYINT        NULL,
    [field02validation]  VARCHAR (50)   NULL,
    [field02post]        VARCHAR (200)  NULL,
    [field03name]        VARCHAR (50)   NULL,
    [field03title]       VARCHAR (100)  NULL,
    [field03typeID]      INT            NULL,
    [field03value]       VARCHAR (100)  NULL,
    [field03len]         INT            NULL,
    [field03lines]       INT            NULL,
    [field03required]    TINYINT        NULL,
    [field03validation]  VARCHAR (50)   NULL,
    [field03post]        VARCHAR (200)  NULL,
    [field04name]        VARCHAR (50)   NULL,
    [field04title]       VARCHAR (100)  NULL,
    [field04typeID]      INT            NULL,
    [field04value]       VARCHAR (100)  NULL,
    [field04len]         INT            NULL,
    [field04lines]       INT            NULL,
    [field04required]    TINYINT        NULL,
    [field04validation]  VARCHAR (50)   NULL,
    [field04post]        VARCHAR (300)  NULL,
    [field05name]        VARCHAR (50)   NULL,
    [field05title]       VARCHAR (100)  NULL,
    [field05typeID]      INT            NULL,
    [field05value]       VARCHAR (100)  NULL,
    [field05len]         INT            NULL,
    [field05lines]       INT            NULL,
    [field05required]    TINYINT        NULL,
    [field05validation]  VARCHAR (50)   NULL,
    [field05post]        VARCHAR (200)  NULL,
    [field06name]        VARCHAR (50)   NULL,
    [field06title]       VARCHAR (100)  NULL,
    [field06typeID]      INT            NULL,
    [field06value]       VARCHAR (100)  NULL,
    [field06len]         INT            NULL,
    [field06lines]       INT            NULL,
    [field06required]    TINYINT        NULL,
    [field06validation]  VARCHAR (50)   NULL,
    [field06post]        VARCHAR (200)  NULL,
    [field07name]        VARCHAR (50)   NULL,
    [field07title]       VARCHAR (100)  NULL,
    [field07typeID]      INT            NULL,
    [field07value]       VARCHAR (100)  NULL,
    [field07len]         INT            NULL,
    [field07lines]       INT            NULL,
    [field07required]    TINYINT        NULL,
    [field07validation]  VARCHAR (50)   NULL,
    [field07post]        VARCHAR (200)  NULL,
    [field08name]        VARCHAR (50)   NULL,
    [field08title]       VARCHAR (100)  NULL,
    [field08typeID]      INT            NULL,
    [field08value]       VARCHAR (100)  NULL,
    [field08len]         INT            NULL,
    [field08lines]       INT            NULL,
    [field08required]    TINYINT        NULL,
    [field08validation]  VARCHAR (50)   NULL,
    [field08post]        VARCHAR (200)  NULL,
    [field09name]        VARCHAR (50)   NULL,
    [field09title]       VARCHAR (100)  NULL,
    [field09typeID]      INT            NULL,
    [field09value]       VARCHAR (100)  NULL,
    [field09len]         INT            NULL,
    [field09lines]       INT            NULL,
    [field09required]    TINYINT        NULL,
    [field09validation]  VARCHAR (50)   NULL,
    [field09post]        VARCHAR (200)  NULL,
    [field10name]        VARCHAR (50)   NULL,
    [field10title]       VARCHAR (100)  NULL,
    [field10typeID]      INT            NULL,
    [field10value]       VARCHAR (100)  NULL,
    [field10len]         INT            NULL,
    [field10lines]       INT            NULL,
    [field10required]    TINYINT        NULL,
    [field10validation]  VARCHAR (50)   NULL,
    [field10post]        VARCHAR (200)  NULL,
    [field11name]        VARCHAR (50)   NULL,
    [field11title]       VARCHAR (100)  NULL,
    [field11typeID]      INT            NULL,
    [field11value]       VARCHAR (100)  NULL,
    [field11len]         INT            NULL,
    [field11lines]       INT            NULL,
    [field11required]    TINYINT        NULL,
    [field11validation]  VARCHAR (50)   NULL,
    [field11post]        VARCHAR (200)  NULL,
    [field12name]        VARCHAR (50)   NULL,
    [field12title]       VARCHAR (100)  NULL,
    [field12typeID]      INT            NULL,
    [field12value]       VARCHAR (100)  NULL,
    [field12len]         INT            NULL,
    [field12lines]       INT            NULL,
    [field12required]    TINYINT        NULL,
    [field12validation]  VARCHAR (50)   NULL,
    [field12post]        VARCHAR (400)  NULL,
    [field13name]        VARCHAR (50)   NULL,
    [field13title]       VARCHAR (100)  NULL,
    [field13typeID]      INT            NULL,
    [field13value]       VARCHAR (100)  NULL,
    [field13len]         INT            NULL,
    [field13lines]       INT            NULL,
    [field13required]    TINYINT        NULL,
    [field13validation]  VARCHAR (50)   NULL,
    [field13post]        VARCHAR (200)  NULL,
    [field14name]        VARCHAR (50)   NULL,
    [field14title]       VARCHAR (100)  NULL,
    [field14typeID]      INT            NULL,
    [field14value]       VARCHAR (100)  NULL,
    [field14len]         INT            NULL,
    [field14lines]       INT            NULL,
    [field14required]    TINYINT        NULL,
    [field14validation]  VARCHAR (50)   NULL,
    [field14post]        VARCHAR (200)  NULL,
    [field15name]        VARCHAR (50)   NULL,
    [field15title]       VARCHAR (100)  NULL,
    [field15typeID]      INT            NULL,
    [field15value]       VARCHAR (100)  NULL,
    [field15len]         INT            NULL,
    [field15lines]       INT            NULL,
    [field15required]    TINYINT        NULL,
    [field15validation]  VARCHAR (50)   NULL,
    [field15post]        VARCHAR (200)  NULL,
    [field16name]        VARCHAR (50)   NULL,
    [field16title]       VARCHAR (100)  NULL,
    [field16typeID]      INT            NULL,
    [field16value]       VARCHAR (100)  NULL,
    [field16len]         INT            NULL,
    [field16lines]       INT            NULL,
    [field16required]    TINYINT        NULL,
    [field16validation]  VARCHAR (50)   NULL,
    [field16post]        VARCHAR (200)  NULL,
    [field17name]        VARCHAR (50)   NULL,
    [field17title]       VARCHAR (100)  NULL,
    [field17typeID]      INT            NULL,
    [field17value]       VARCHAR (100)  NULL,
    [field17len]         INT            NULL,
    [field17lines]       INT            NULL,
    [field17required]    TINYINT        NULL,
    [field17validation]  VARCHAR (50)   NULL,
    [field17post]        VARCHAR (200)  NULL,
    [field18name]        VARCHAR (50)   NULL,
    [field18title]       VARCHAR (100)  NULL,
    [field18typeID]      INT            NULL,
    [field18value]       VARCHAR (100)  NULL,
    [field18len]         INT            NULL,
    [field18lines]       INT            NULL,
    [field18required]    TINYINT        NULL,
    [field18validation]  VARCHAR (50)   NULL,
    [field18post]        VARCHAR (200)  NULL,
    [field19name]        VARCHAR (50)   NULL,
    [field19title]       VARCHAR (100)  NULL,
    [field19typeID]      INT            NULL,
    [field19value]       VARCHAR (100)  NULL,
    [field19len]         INT            NULL,
    [field19lines]       INT            NULL,
    [field19required]    TINYINT        NULL,
    [field19validation]  VARCHAR (50)   NULL,
    [field19post]        VARCHAR (200)  NULL,
    [field20name]        VARCHAR (50)   NULL,
    [field20title]       VARCHAR (100)  NULL,
    [field20typeID]      INT            NULL,
    [field20value]       VARCHAR (100)  NULL,
    [field20len]         INT            NULL,
    [field20lines]       INT            NULL,
    [field20required]    TINYINT        NULL,
    [field20validation]  VARCHAR (50)   NULL,
    [field20post]        VARCHAR (200)  NULL,
    [field21name]        VARCHAR (50)   NULL,
    [field21title]       VARCHAR (300)  NULL,
    [field21typeID]      INT            NULL,
    [field21value]       VARCHAR (100)  NULL,
    [field21len]         INT            NULL,
    [field21lines]       INT            NULL,
    [field21required]    TINYINT        NULL,
    [field21validation]  VARCHAR (50)   NULL,
    [field21post]        VARCHAR (200)  NULL,
    [field22name]        VARCHAR (50)   NULL,
    [field22title]       VARCHAR (300)  NULL,
    [field22typeID]      INT            NULL,
    [field22value]       VARCHAR (100)  NULL,
    [field22len]         INT            NULL,
    [field22lines]       INT            NULL,
    [field22required]    TINYINT        NULL,
    [field22validation]  VARCHAR (50)   NULL,
    [field22post]        VARCHAR (200)  NULL,
    [field23name]        VARCHAR (50)   NULL,
    [field23title]       VARCHAR (300)  NULL,
    [field23typeID]      INT            NULL,
    [field23value]       VARCHAR (100)  NULL,
    [field23len]         INT            NULL,
    [field23lines]       INT            NULL,
    [field23required]    TINYINT        NULL,
    [field23validation]  VARCHAR (50)   NULL,
    [field23post]        VARCHAR (200)  NULL,
    [field24name]        VARCHAR (50)   NULL,
    [field24title]       VARCHAR (100)  NULL,
    [field24typeID]      INT            NULL,
    [field24value]       VARCHAR (100)  NULL,
    [field24len]         INT            NULL,
    [field24lines]       INT            NULL,
    [field24required]    TINYINT        NULL,
    [field24validation]  VARCHAR (50)   NULL,
    [field24post]        VARCHAR (200)  NULL,
    [field25name]        VARCHAR (50)   NULL,
    [field25title]       VARCHAR (100)  NULL,
    [field25typeID]      INT            NULL,
    [field25value]       VARCHAR (100)  NULL,
    [field25len]         INT            NULL,
    [field25lines]       INT            NULL,
    [field25required]    TINYINT        NULL,
    [field25validation]  VARCHAR (50)   NULL,
    [field25post]        VARCHAR (200)  NULL,
    [field26name]        VARCHAR (50)   NULL,
    [field26title]       VARCHAR (100)  NULL,
    [field26typeID]      INT            NULL,
    [field26value]       VARCHAR (100)  NULL,
    [field26len]         INT            NULL,
    [field26lines]       INT            NULL,
    [field26required]    TINYINT        NULL,
    [field26validation]  VARCHAR (50)   NULL,
    [field26post]        VARCHAR (200)  NULL,
    [field27name]        VARCHAR (50)   NULL,
    [field27title]       VARCHAR (100)  NULL,
    [field27typeID]      INT            NULL,
    [field27value]       VARCHAR (100)  NULL,
    [field27len]         INT            NULL,
    [field27lines]       INT            NULL,
    [field27required]    TINYINT        NULL,
    [field27validation]  VARCHAR (50)   NULL,
    [field27post]        VARCHAR (2000) NULL,
    [field28name]        VARCHAR (50)   NULL,
    [field28title]       VARCHAR (100)  NULL,
    [field28typeID]      INT            NULL,
    [field28value]       VARCHAR (100)  NULL,
    [field28len]         INT            NULL,
    [field28lines]       INT            NULL,
    [field28required]    TINYINT        NULL,
    [field28validation]  VARCHAR (50)   NULL,
    [field28post]        VARCHAR (200)  NULL,
    [field29name]        VARCHAR (50)   NULL,
    [field29title]       VARCHAR (100)  NULL,
    [field29typeID]      INT            NULL,
    [field29value]       VARCHAR (100)  NULL,
    [field29len]         INT            NULL,
    [field29lines]       INT            NULL,
    [field29required]    TINYINT        NULL,
    [field29validation]  VARCHAR (50)   NULL,
    [field29post]        VARCHAR (200)  NULL,
    [field30name]        VARCHAR (50)   NULL,
    [field30title]       VARCHAR (100)  NULL,
    [field30typeID]      INT            NULL,
    [field30value]       VARCHAR (100)  NULL,
    [field30len]         INT            NULL,
    [field30lines]       INT            NULL,
    [field30required]    TINYINT        NULL,
    [field30validation]  VARCHAR (50)   NULL,
    [field30post]        VARCHAR (200)  NULL,
    CONSTRAINT [PK_mailforms] PRIMARY KEY CLUSTERED ([mailformID] ASC) WITH (FILLFACTOR = 90)
);




GO
GRANT UPDATE
    ON OBJECT::[dbo].[mailforms] TO [wfjuser]
    AS [dbo];




GO
GRANT SELECT
    ON OBJECT::[dbo].[mailforms] TO [wfjuser]
    AS [dbo];




GO
GRANT INSERT
    ON OBJECT::[dbo].[mailforms] TO [wfjuser]
    AS [dbo];




GO
GRANT DELETE
    ON OBJECT::[dbo].[mailforms] TO [wfjuser]
    AS [dbo];



